
export enum Tags {
    NextJS = "Next.js",
    TailwindCSS = "Tailwind CSS",
    React = "React",
    JavaScript = "JavaScript",
    TypeScript = "TypeScript",
    Redux = "Redux Toolkit",
    Zustand = "Zustand",
    MUI = "Material UI",
    ChakraUI = "Chakra UI",
    PrimeReact = "PrimeReact",
    ApexCharts = "ApexCharts",
    Highcharts = "Highcharts.js",
    WordPress = "WordPress",
    Astra = "Astra",
    Gatsby = "Gatsby",
    Contenful = "Contenful",
    Hubspot = "Hubspot",
    Shopify = "Shopify",
    Storybook = "Storybook",
    ReactHookForm = "React Hook Form",
    Prisma = "Prisma",
    NextAuth = "NextAuth",
    Vercel = "Vercel",
    CSS = "CSS",
    HTML = "HTML",
    LinkedIn = "LinkedIn",
    Github = "Github",
    jQuery = "jQuery",
    AlpineJs = "Alpine.js",

}